### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by Antisa14200** [gamesukimanIRS/StairSeatDown#1]
ParseError: "syntax error, unexpected ';', expecting ',' or ')'" (EXCEPTION) in "StairSeatDown-master/src/StairSeatDown/Main" at line 69

**Comment by FienixEC** [comment]
@Antisa14200 
$player->sendPopup($this->get("touch-popup");
                                                            add " ) "   ^

but this plugin still has several issues beyond just this, would wait for the dev complete it further

**Comment by gamesukimanIRS** [comment]
Fixed.
Thank you for your report.

**Comment by gamesukimanIRS** [comment]
Since it is not yet perfect, please report it if you find a bug.
