### ISSUE TITLE
[Warning] LGPL violation

### ISSUE THREAD

**Issue by fuyutsuki** [gamesukimanIRS/StairSeatDown#2]
## This issue is notification of LGPL violation.
この問題はLGPL違反の通知です。

## 問題点
PMChairの派生プラグインであるため、このプラグインは **LGPL** もしくは **GPL** を適用する必要があります。  

また、この問題が修正されない場合は ___MCBE-JPNからの追放処分などの措置を取る可能性があります___。

**Comment by gamesukimanIRS** [comment]
ライセンスの解釈に誤りがあったため、ライセンスをLGPLに変更致しました。
申し訳ございませんでした。
