### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Antisa14200** [gamesukimanIRS/StairSeatDown#3]
I bet you may notice this, but anyway reporting it

While loading

 [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '$this' (T_VARIABLE)" (EXCEPTION) in "StairSeatDown-master/src/StairSeatDown/Main" at line 30

**Comment by gamesukimanIRS** [comment]
Oh, sorry.
Thank you for the report. Fixed.

**Comment by Antisa14200** [comment]
Is there a way to change language to English tho?
Bcs in messages.yml I can't really find it 

Btw, plugin loads fine but this error appears when trying to sit

[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'StairSeatDown v1.0.0': Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putEntityLink() must be an instance of pocketmine\network\mcpe\protocol\types\EntityLink, array given, called in phar://F:/PocketMine 19133/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 112 on StairSeatDown\Main
 [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putEntityLink() must be an instance of pocketmine\network\mcpe\protocol\types\EntityLink, array given, called in phar://F:/PocketMine 19133/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 112" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 517

**Comment by gamesukimanIRS** [comment]
I am busy now, so I will fix it next time. I will let you know when I fix it.

**Comment by Antisa14200** [comment]
Alright np, when you can

Dana 19. sij 2018. 08:44 osoba "gamesukimanIRS" <notifications@github.com>
napisala je:
